var target = "joesguns";
var moneyThresh = getServerMaxMoney(target) * 0.60;
var securityThresh = getServerMinSecurityLevel(target);

while (!fileExists("BruteSSH.exe", "home")) {
    sleep(10000);
}
brutessh(target);
nuke(target);

// Infinite loop that continously hacks/grows/weakens the target server
while (true) {
    if (getServerSecurityLevel(target) > securityThresh + 10) {
        // If the server's security level is above our threshold, weaken it
        weaken(target);
    } else if (getServerMoneyAvailable(target) < moneyThresh) {
        // If the server's money is less than our threshold, grow it
        grow(target);
    } else {
        // Otherwise, hack it
        hack(target);
    }
}